search_field = 'input[aria-label="Search"]'
shoes = 'a[data-at="product"]'
shoes_size = '//div[@id="app"]//div//button[text()="UK 7"]'
add_to_bag = 'button[data-at="add-to-bag"]'
view_cart = "div.css-172e7gk"
procced_to_buy = 'button[data-at="continue-to-checkout"]'
iframe = 'iframe[title="Nykaa Fashion Cart"]'
procced_to_pay = '//div//button[text()="Proceed to Pay"]'
conformation_msg = '//div[@id="portal-root"]//p[text()="You have successfully signed up! Enjoy the shopping at Nykaa Fashion"]'
you_pay = '//div//dt[text()="You Pay"]'
